EMOTION_POOLS = {
    "anger": ["volcanic emotional eruption", "acute indignation response"],
    "tired": ["profound existential fatigue", "terminal exhaustion"],
    "sad": ["deep melancholic resonance", "low-frequency suffering"],
    "frustrated": ["psychological friction buildup", "mounting exasperation"],
    "anxious": ["anticipatory dread", "chronic uncertainty response"]
}

EMOTION_KEYWORDS = {
    "anger": [
        "angry","furious","rage","hate","pissed","mad","livid","fuming","resentful",
        "bitter","hostile","outraged","irate","seething","explosive","vengeful","wrathful",
        "incensed","inflamed","enraged","infuriated","aggravated","antagonized","provoked",
        "irritated","heated","boiling","snapping","storming","erupting","venting","raging",
        "combative","aggressive","violent","spiteful","vindictive","contemptuous","scornful",
        "disgusted","offended","insulted","betrayed","crossed","triggered","fed up","done",
        "volcanic","nuclear","savage","feral","frothing","snarling","growling","gnashing",
        "murderous","homicidal","ballistic","unhinged","uncontrolled","unleashed","rabid",
        "blinding","white-hot","scorching","burning","blazing","searing","scorched","scalded",
        "wronged","stabbed","used","exploited","manipulated","lied to","deceived","cheated",
        "disrespected","humiliated","degraded","dismissed","undervalued","overlooked","ignored",
        "gaslit","blamed","scapegoated","punished","targeted","cornered","railroaded","set up",
        "annoyed","irked","bothered","bugged","vexed","nettled","rankled","chafed","peeved",
        "displeased","dissatisfied","impatient","intolerant","short-fused","terse","clipped",
        "cold","cutting","sharp","curt","harsh","blunt","biting","caustic","acid","scathing",
        "shaking","trembling","clenched","jaw tight","fists","teeth","rigid","tense","locked",
        "stomping","slamming","throwing","breaking","screaming","yelling","shouting","snapping",
        "revolted","repulsed","sickened","nauseated","appalled","horrified","shocked","aghast",
        "superior","disdainful","sneering","mocking","ridiculing","dismissive",
        "i hate","i can't stand","drives me insane","makes me sick","i'm done","enough",
        "screw this","screw that","forget it","i give up fighting","no more","never again",
    ],
    "tired": [
        "tired","exhausted","drained","burnout","fatigue","depleted","overworked",
        "weary","sleepy","sluggish","worn","spent","hollow","heavy","foggy","numb",
        "lifeless","listless","lethargic","drowsy","groggy","half-awake","running on empty",
        "collapsing","barely functioning","dead on my feet","zapped","wiped","done in",
        "flat","blunted","slow","shutdown","fading","dim","running low","no energy",
        "degraded","deteriorating","eroding","burning out","worn thin","fraying","unraveling",
        "aching","sore","stiff","heavy limbs","lead legs","concrete","weighted","dragging",
        "stumbling","swaying","drooping","slumping","slouching","sinking","crumpling","folding",
        "eyes heavy","vision blurring","hands shaking","body failing","legs giving","floor calling",
        "brain dead","mind blank","can't think","no thoughts","fuzzy","cloudy","hazy",
        "scattered","fragmented","disconnected","zoned out","checked out","autopilot","absent",
        "slow processing","delayed","lagging","buffering","offline","unreachable","gone",
        "apathetic","indifferent","detached","dissociated","removed","distant","far away",
        "no feeling","beyond feeling","past caring","too tired to care","too tired to feel",
        "insomniac","sleep deprived","no sleep","restless","unrefreshed","broken sleep","wrecked",
        "oversleeping","can't wake","waking exhausted","never rested","always tired","perpetually",
        "chronically tired","always this","no end","cycle","trapped in exhaustion","never recovers",
        "years of this","cumulative","compounding","getting worse","downward","spiral","decline",
        "i can't","i just can't","not today","done","finished","no more","i need to stop",
        "i need rest","leave me alone","just let me sleep","too much","can't keep going",
    ],
    "sad": [
        "sad","cry","miserable","depressed","empty","lonely","numb",
        "heartbroken","grief","mourning","sorrowful","hopeless","hollow","lost",
        "abandoned","forgotten","invisible","unloved","unwanted","disconnected",
        "withdrawn","isolating","fading","disappearing","crying","sobbing","weeping",
        "aching","heavy","dark","bleak","gloomy","joyless","colorless","quiet inside",
        "defeated","broken","shattered","crushed","devastated","beyond words","gone",
        "adrift","untethered","without anchor","sinking","slipping","disappearing slowly",
        "grieving","loss","bereaved","missing","yearning","longing","pining","wishing",
        "nostalgic","reminiscing","haunted","visiting old memories","can't let go","holding on",
        "hopeless","pointless","meaningless","worthless","what's the point","nothing matters",
        "no future","no way forward","no path","stuck forever","it won't change","always this",
        "never better","getting worse","downward","falling","no bottom","endless","infinite",
        "alone","by myself","no one","nobody","not understood","not seen","not heard",
        "glass wall","watching from outside","can't connect","can't reach","unreachable","sealed",
        "room full of people alone","surrounded but empty","present but absent","there but gone",
        "heavy chest","tight throat","tears","wet face","red eyes","swollen",
        "curled up","fetal","under covers","can't move","won't move","still","motionless","quiet",
        "wistful","pensive","reflective","subdued","soft","gray","pale","dim",
        "low","under","beneath","below","down","deep","far","distant","behind glass","muffled",
        "anhedonic","no pleasure","nothing enjoyable","everything grey","colors gone","flat world",
        "no motivation","no drive","no desire","no appetite","no interest","no will","no point",
        "i miss","i miss them","i miss it","i miss who i was","i miss feeling okay","i miss normal",
        "i don't know why i'm crying","i just feel sad","i can't explain it","it just hurts",
    ],
    "frustrated": [
        "frustrated","annoying","stupid","ugh","pointless","broken","useless",
        "stuck","blocked","stalled","trapped","spinning","looping","going nowhere",
        "wasted","futile","absurd","ridiculous","maddening","infuriating",
        "incompetent","terrible","awful","disaster","failure","mistake","wrong again",
        "not working","keeps breaking","nothing works","every time","always this","again",
        "why bother","can't win","rigged","impossible","unreasonable",
        "ignored","dismissed","shut down","unheard","hit a wall","no progress","dead end",
        "over it","done trying","finished","giving up","not worth it",
        "obstructed","hindered","impeded","prevented","stopped","halted","frozen","locked",
        "no way through","closed off","cut off","denied","refused","rejected","overruled",
        "vetoed","overturned","reversed","undone","reset","back to zero","starting over again",
        "same thing","always the same","never changes","broken record",
        "cycle","loop","repeat","groundhog day","same wall","same block","same error",
        "third time","tenth time","hundredth time","still","still not fixed","still broken",
        "no one knows","no one helps","no one cares","inept","clueless",
        "wrong person","wrong answer","wrong direction","misunderstood","miscommunicated","missed",
        "tried everything","nothing helps","hours wasted","days wasted","for nothing",
        "no payoff","no reward","no result","no outcome","empty hands","zero",
        "ugh","argh","seriously","really","come on","are you kidding","unbelievable","unreal",
        "i give up","i quit","that's it","i'm done","forget it","whatever","fine",
        "this is stupid","this is broken","this is a joke","this is useless","this is impossible",
        "helpless","powerless","no control","no agency","no say","no choice","no option","cornered",
        "between walls","no room","no exit","no solution","no answer","no fix","no way","nothing",
    ],
    "anxious": [
        "anxious","worried","stress","panic","overwhelmed","nervous","on edge",
        "afraid","scared","fearful","dreading","apprehensive","uneasy","restless",
        "tense","tight","wound up","bracing","anticipating","spiraling","catastrophizing",
        "can't breathe","heart racing","shaking","trembling","frozen","paralyzed",
        "can't focus","mind racing","intrusive thoughts","worst case","something's wrong",
        "not safe","impending","looming","pressure building","too much","can't handle",
        "losing control","unraveling","fragile","breaking point","about to snap",
        "hypervigilant","scanning","watching","waiting","something's coming","too loud",
        "chest tight","chest heavy","can't inhale","shallow breath","short breath","no air",
        "heart pounding","pulse loud","pulse fast","blood rushing","ears ringing","dizzy",
        "nauseous","sick","stomach dropping","gut clenched","stomach flipping","queasy",
        "sweating","cold sweat","clammy","flush","hot face","cold hands","pins and needles",
        "legs weak","knees soft","hands shaking","voice shaking","jaw clenched","shoulders up",
        "racing thoughts","can't stop thinking","mind won't quiet","circling",
        "what if","but what if","and then what","worst case","it'll go wrong",
        "something bad","disaster coming","it's all going to fall apart","i know it","i feel it",
        "judged","watched","observed","evaluated","assessed","measured","found lacking",
        "embarrassed","humiliated","awkward","out of place","don't belong","too visible","exposed",
        "said the wrong thing","did the wrong thing","they noticed","they know","they think",
        "uncertain","unknown","unpredictable","uncontrollable","random","arbitrary","no pattern",
        "no ground","no floor","no foundation","nothing solid","shifting","moving","unstable",
        "no certainty","no guarantee","no promise","no safety","no anchor","floating","unmoored",
        "too many things","too many tabs","too many tasks","too many people","too many voices",
        "all at once","simultaneously","piling up","stacking","compounding","multiplying","growing",
        "no end","no break","no pause","no quiet","no space","no room","suffocating","drowning",
        "i can't do this","i can't handle this","i'm not okay","something's wrong","i'm scared",
        "i don't feel safe","i feel it coming","i'm losing it","i'm falling apart","i can't calm down",
    ],
}

WING_NAMES = [
    "Wing 1","Wing 2","Wing 3","Wing 4","Wing 5","Wing 6","Wing 7","Wing 8","Wing 9","Wing 10",
    "Wing A","Wing B","Wing C","Wing D","Wing E","Wing F","Wing G","Wing H","Wing I","Wing J",
    "North Wing","South Wing","East Wing","West Wing","Central Wing","Upper Wing","Lower Wing",
    "Terminal Wing","Overflow Wing","Auxiliary Wing","Archive Wing","Recovery Wing",
    "Processing Wing","Intake Wing","Isolation Wing","Holding Wing","Transit Wing",
    "Sector 1","Sector 2","Sector 3","Sector 4","Sector 5","Sector 6","Sector 7","Sector 8",
    "Block A","Block B","Block C","Block D","Block E","Block F","Block G","Block H",
    "Unit 1","Unit 2","Unit 3","Unit 4","Unit 5","Unit 6","Unit 7","Unit 8","Unit 9","Unit 10",
    "Ward 1","Ward 2","Ward 3","Ward 4","Ward 5","Ward 6","Ward 7","Ward 8","Ward 9","Ward 10",
    "Division I","Division II","Division III","Division IV","Division V",
    "Zone Alpha","Zone Beta","Zone Gamma","Zone Delta","Zone Epsilon","Zone Theta","Zone Sigma",
    "Level 0","Level 1","Level 2","Level 3","Level 4","Level 5","Level 6","Level 7",
    "Corridor 1","Corridor 2","Corridor 3","Corridor 4","Corridor 5","Corridor 6",
    "Chamber A","Chamber B","Chamber C","Chamber D","Chamber E","Chamber F",
    "Annex 1","Annex 2","Annex 3","Annex 4","Annex 5","Annex 6","Annex 7",
    "Bay 1","Bay 2","Bay 3","Bay 4","Bay 5","Bay 6","Bay 7","Bay 8","Bay 9","Bay 10",
]

SIGNIFICANCE_PHRASES = [
    "offers insight","documents strain","reveals pressure","confirms fatigue",
    "captures distress","indicates overload","shows collapse","records breakdown",
    "reflects tension","demonstrates impact","exposes fracture","marks deterioration",
    "traces decline","logs the rupture","preserves the failure","archives the weight",
    "catalogues the breaking point","indexes despair","charts the unraveling",
    "registers the absence","notes the void","confirms the spiral","maps the collapse",
    "isolates the moment","frames the crisis","captures the silence","records the gap",
    "preserves the damage","marks the threshold","crosses the limit","notes the pattern",
    "documents the repeat","logs recurrence","identifies the loop","confirms the trend",
    "shows no improvement","reveals ongoing strain","marks continued distress",
    "flags unresolved tension","highlights the gap","exposes systemic pressure",
    "records without resolution","archives the aftermath","preserves without comment",
    "notes without intervention","logs without closure","captures the remainder",
]

CURATOR_NOTES = [
    "Recovered alongside tasks.","No resolution.","Mid-collapse.","Staff uneasy.",
    "Found unstable.","Entry rushed.","No edits.","Emotion dense.","No closure.",
    "Fragment incomplete.","Handwriting deteriorated.","Submitted without review.",
    "Filed in error.","Duplicate entry.","Source unclear.","Context missing.",
    "Recovered from discard pile.","Noted and shelved.","Unverified origin.",
    "No follow-up recorded.","Left at workstation.","Printed and abandoned.",
    "Timestamp inconsistent.","Author unconfirmed.","Condition: fragile.",
    "Found folded.","Ink smeared.","Pages missing.","Partially illegible.",
    "No signature.","Submitted anonymously.","No department listed.",
    "Recovery date unknown.","Catalogued posthumously.","Cross-referenced: nothing.",
    "No matching file.","No known author.","No related incident report.",
    "Emotion flagged, no action taken.","Reviewed once, not again.",
    "Noted by archivist.","Assigned no case number.","No escalation.",
    "No referral made.","No support offered.","Processed. Archived. Closed.",
    "No further entries.","Last entry in sequence.","Nothing follows this.",
    "Intervention: none recorded.","Outcome: unknown.","Status: unresolved.",
    "Condition at recovery: poor.","Tears detected on page.","Stain of unknown origin.",
    "Edges worn.","Cover detached.","Binding failed.","Pages out of order.",
    "Recovered incomplete.","Final page missing.","Beginning absent.",
]

FOOTNOTES = [
    "† No resolution.","† Ongoing.","† Incomplete.","† Repeating.","† Aware.",
    "† No intervention.","† Missing context.","† High load.","† No support.",
    "† Unresolved.","† Pattern confirmed.","† Recurrence noted.","† No referral.",
    "† Escalation absent.","† Flagged only.","† Reviewed, not addressed.",
    "† Acknowledged. Shelved.","† Closed without outcome.","† No follow-up.",
    "† Author unknown.","† Origin unclear.","† Date inconsistent.","† Unverified.",
    "† Partial record only.","† Pages missing.","† Entry cut short.",
    "† No conclusion reached.","† Loop continues.","† Cycle unbroken.",
    "† No improvement logged.","† Decline documented.","† Threshold crossed.",
    "† Intervention: none.","† Support: none.","† Outcome: absent.",
    "† Remains open.","† Still active.","† Continuing.","† Not resolved.",
    "† Filed and forgotten.","† Archived without action.","† No case opened.",
    "† Noted by no one.","† Observed. Ignored.","† Witnessed. Uncatalogued.",
    "† Weight persists.","† Pressure maintained.","† Load unchanged.",
    "† No relief recorded.","† Condition stable at: critical.","† Holding, barely.",
    "† Last entry in series.","† Nothing follows.","† End of record.",
]

DRAMATIC_ADJECTIVES = [
    "The Great","The Terminal","The Unfinished","The Inevitable","The Silent",
    "The Unresolved","The Final","The Persistent","The Lingering","The Recorded",
    "The Slow","The Quiet","The Hidden","The Documented","The Witnessed",
    "The Archived","The Forgotten","The Catalogued","The Preserved","The Flagged",
    "The Unremarkable","The Ordinary","The Daily","The Chronic","The Systemic",
    "The Repeated","The Predictable","The Expected","The Scheduled","The Routine",
    "The Measured","The Indexed","The Filed","The Logged","The Entered",
    "The Visible","The Legible","The Quantified","The Stamped","The Dated",
    "The Known","The Confirmed","The Verified","The Identified","The Classified",
    "The Acute","The Prolonged","The Extended","The Cumulative","The Progressive",
    "The Compounding","The Escalating","The Accelerating","The Deepening",
    "The Widening","The Spreading","The Encroaching","The Advancing","The Settling",
    "The Absolute","The Total","The Complete","The Thorough","The Comprehensive",
    "The Partial","The Fractured","The Broken","The Collapsed","The Fallen",
    "The Last","The First","The Only","The Single","The Solitary","The Lone",
    "The Heavy","The Dense","The Thick","The Dark","The Cold","The Empty",
    "The Hollow","The Blank","The Still","The Flat","The Gray","The Distant",
]

ARTIFACT_NOUNS = {
    "anger": [
        "Fury","Rupture","Flashpoint","Surge","Outburst","Spike","Burst","Flare","Break","Reaction",
        "Ignition","Detonation","Explosion","Eruption","Blowout","Discharge","Release","Fracture",
        "Collision","Impact","Strike","Blow","Crack","Split","Shatter","Tear","Rip","Snap",
        "Rebellion","Revolt","Refusal","Rejection","Defiance","Resistance","Confrontation","Challenge",
        "Boiling Point","Threshold","Limit","Edge","Boundary","Line","Wall","Ceiling","Floor","End",
        "Wave","Storm","Tempest","Torrent","Flood","Current","Tide","Force","Pressure","Charge",
    ],
    "tired": [
        "Collapse","Exhaustion","Decline","Drain","Depletion","Fade","Drop","Shutdown","Slowdown","Dimming",
        "Descent","Erosion","Degradation","Deterioration","Dissolution","Dissipation","Attrition","Wearing",
        "Flicker","Dimmer","Outage","Blackout","Failure","Halt","Stop","End","Cessation",
        "Quiet","Stillness","Silence","Pause","Rest","Stasis","Suspension","Dormancy","Hibernation",
        "Weight","Heaviness","Gravity","Burden","Load","Mass","Density","Thickness","Saturation",
        "Fog","Haze","Blur","Drift","Float","Limbo","Nowhere","Absence","Void",
    ],
    "sad": [
        "Lament","Grief","Weight","Absence","Loss","Echo","Hollow","Drift","Fade","Descent",
        "Mourning","Elegy","Requiem","Dirge","Farewell","Goodbye","Ending","Closing","Departure","Exit",
        "Silence","Void","Emptiness","Nothing","Gap","Space","Distance","Separation","Division","Break",
        "Ache","Wound","Scar","Mark","Trace","Remnant","Relic","Fragment","Shard","Piece",
        "Memory","Ghost","Shadow","Reflection","Echo","Impression","Imprint","Residue","Remainder","Afterimage",
        "Rain","Fog","Dark","Gray","Cold","Still","Heavy","Slow","Low","Down",
    ],
    "frustrated": [
        "Impasse","Friction","Gridlock","Snag","Block","Jam","Loop","Clog","Barrier","Deadlock",
        "Wall","Ceiling","Floor","Limit","Boundary","Edge","Border","Line","Threshold","Cap",
        "Stall","Halt","Stop","Freeze","Lock","Bind","Trap","Cage","Cell","Enclosure",
        "Cycle","Circle","Spin","Repeat","Recurrence","Pattern","Routine","Rut","Groove",
        "Failure","Error","Mistake","Fault","Flaw","Bug","Glitch","Break","Crack","Gap",
        "Void","Absence","Hole","Disconnect","Mismatch","Conflict","Contradiction","Paradox",
    ],
"anxious": [
        "anxious","worried","stress","panic","overwhelmed","nervous","on edge",
        "afraid","scared","fearful","dreading","apprehensive","uneasy","restless",
        "tense","tight","wound up","bracing","anticipating","spiraling","catastrophizing",
        "can't breathe","heart racing","shaking","trembling","frozen","paralyzed",
        "can't focus","mind racing","intrusive thoughts","worst case","something's wrong",
        "not safe","impending","looming","pressure building","too much","can't handle",
        "losing control","unraveling","fragile","breaking point","about to snap",
        "hypervigilant","scanning","watching","waiting","something's coming","too loud",
        "chest tight","chest heavy","can't inhale","shallow breath","short breath","no air",
        "heart pounding","pulse loud","pulse fast","blood rushing","ears ringing","dizzy",
        "nauseous","sick","stomach dropping","gut clenched","stomach flipping","queasy",
        "sweating","cold sweat","clammy","flush","hot face","cold hands","pins and needles",
        "legs weak","knees soft","hands shaking","voice shaking","jaw clenched","shoulders up",
        "racing thoughts","can't stop thinking","mind won't quiet","circling",
        "what if","but what if","and then what","worst case","it'll go wrong",
        "something bad","disaster coming","it's all going to fall apart","i know it","i feel it",
        "judged","watched","observed","evaluated","assessed","measured","found lacking",
        "embarrassed","humiliated","awkward","out of place","don't belong","too visible","exposed",
        "said the wrong thing","did the wrong thing","they noticed","they know","they think",
        "uncertain","unknown","unpredictable","uncontrollable","random","arbitrary","no pattern",
        "no ground","no floor","no foundation","nothing solid","shifting","moving","unstable",
        "no certainty","no guarantee","no promise","no safety","no anchor","floating","unmoored",
        "too many things","too many tabs","too many tasks","too many people","too many voices",
        "all at once","simultaneously","piling up","stacking","compounding","multiplying","growing",
        "no end","no break","no pause","no quiet","no space","no room","suffocating","drowning",
        "i can't do this","i can't handle this","i'm not okay","something's wrong","i'm scared",
        "i don't feel safe","i feel it coming","i'm losing it","i'm falling apart","i can't calm down",
    ],
}

WING_NAMES = [
    "Wing 1","Wing 2","Wing 3","Wing 4","Wing 5","Wing 6","Wing 7","Wing 8","Wing 9","Wing 10",
    "Wing A","Wing B","Wing C","Wing D","Wing E","Wing F","Wing G","Wing H","Wing I","Wing J",
    "North Wing","South Wing","East Wing","West Wing","Central Wing","Upper Wing","Lower Wing",
    "Terminal Wing","Overflow Wing","Auxiliary Wing","Archive Wing","Recovery Wing",
    "Processing Wing","Intake Wing","Isolation Wing","Holding Wing","Transit Wing",
    "Sector 1","Sector 2","Sector 3","Sector 4","Sector 5","Sector 6","Sector 7","Sector 8",
    "Block A","Block B","Block C","Block D","Block E","Block F","Block G","Block H",
    "Unit 1","Unit 2","Unit 3","Unit 4","Unit 5","Unit 6","Unit 7","Unit 8","Unit 9","Unit 10",
    "Ward 1","Ward 2","Ward 3","Ward 4","Ward 5","Ward 6","Ward 7","Ward 8","Ward 9","Ward 10",
    "Division I","Division II","Division III","Division IV","Division V",
    "Zone Alpha","Zone Beta","Zone Gamma","Zone Delta","Zone Epsilon","Zone Theta","Zone Sigma",
    "Level 0","Level 1","Level 2","Level 3","Level 4","Level 5","Level 6","Level 7",
    "Corridor 1","Corridor 2","Corridor 3","Corridor 4","Corridor 5","Corridor 6",
    "Chamber A","Chamber B","Chamber C","Chamber D","Chamber E","Chamber F",
    "Annex 1","Annex 2","Annex 3","Annex 4","Annex 5","Annex 6","Annex 7",
    "Bay 1","Bay 2","Bay 3","Bay 4","Bay 5","Bay 6","Bay 7","Bay 8","Bay 9","Bay 10",
]

SIGNIFICANCE_PHRASES = [
    "offers insight","documents strain","reveals pressure","confirms fatigue",
    "captures distress","indicates overload","shows collapse","records breakdown",
    "reflects tension","demonstrates impact","exposes fracture","marks deterioration",
    "traces decline","logs the rupture","preserves the failure","archives the weight",
    "catalogues the breaking point","indexes despair","charts the unraveling",
    "registers the absence","notes the void","confirms the spiral","maps the collapse",
    "isolates the moment","frames the crisis","captures the silence","records the gap",
    "preserves the damage","marks the threshold","crosses the limit","notes the pattern",
    "documents the repeat","logs recurrence","identifies the loop","confirms the trend",
    "shows no improvement","reveals ongoing strain","marks continued distress",
    "flags unresolved tension","highlights the gap","exposes systemic pressure",
    "records without resolution","archives the aftermath","preserves without comment",
    "notes without intervention","logs without closure","captures the remainder",
]

CURATOR_NOTES = [
    "Recovered alongside tasks.","No resolution.","Mid-collapse.","Staff uneasy.",
    "Found unstable.","Entry rushed.","No edits.","Emotion dense.","No closure.",
    "Fragment incomplete.","Handwriting deteriorated.","Submitted without review.",
    "Filed in error.","Duplicate entry.","Source unclear.","Context missing.",
    "Recovered from discard pile.","Noted and shelved.","Unverified origin.",
    "No follow-up recorded.","Left at workstation.","Printed and abandoned.",
    "Timestamp inconsistent.","Author unconfirmed.","Condition: fragile.",
    "Found folded.","Ink smeared.","Pages missing.","Partially illegible.",
    "No signature.","Submitted anonymously.","No department listed.",
    "Recovery date unknown.","Catalogued posthumously.","Cross-referenced: nothing.",
    "No matching file.","No known author.","No related incident report.",
    "Emotion flagged, no action taken.","Reviewed once, not again.",
    "Noted by archivist.","Assigned no case number.","No escalation.",
    "No referral made.","No support offered.","Processed. Archived. Closed.",
    "No further entries.","Last entry in sequence.","Nothing follows this.",
    "Intervention: none recorded.","Outcome: unknown.","Status: unresolved.",
    "Condition at recovery: poor.","Tears detected on page.","Stain of unknown origin.",
    "Edges worn.","Cover detached.","Binding failed.","Pages out of order.",
    "Recovered incomplete.","Final page missing.","Beginning absent.",
]

FOOTNOTES = [
    "† No resolution.","† Ongoing.","† Incomplete.","† Repeating.","† Aware.",
    "† No intervention.","† Missing context.","† High load.","† No support.",
    "† Unresolved.","† Pattern confirmed.","† Recurrence noted.","† No referral.",
    "† Escalation absent.","† Flagged only.","† Reviewed, not addressed.",
    "† Acknowledged. Shelved.","† Closed without outcome.","† No follow-up.",
    "† Author unknown.","† Origin unclear.","† Date inconsistent.","† Unverified.",
    "† Partial record only.","† Pages missing.","† Entry cut short.",
    "† No conclusion reached.","† Loop continues.","† Cycle unbroken.",
    "† No improvement logged.","† Decline documented.","† Threshold crossed.",
    "† Intervention: none.","† Support: none.","† Outcome: absent.",
    "† Remains open.","† Still active.","† Continuing.","† Not resolved.",
    "† Filed and forgotten.","† Archived without action.","† No case opened.",
    "† Noted by no one.","† Observed. Ignored.","† Witnessed. Uncatalogued.",
    "† Weight persists.","† Pressure maintained.","† Load unchanged.",
    "† No relief recorded.","† Condition stable at: critical.","† Holding, barely.",
    "† Last entry in series.","† Nothing follows.","† End of record.",
]

DRAMATIC_ADJECTIVES = [
    "The Great","The Terminal","The Unfinished","The Inevitable","The Silent",
    "The Unresolved","The Final","The Persistent","The Lingering","The Recorded",
    "The Slow","The Quiet","The Hidden","The Documented","The Witnessed",
    "The Archived","The Forgotten","The Catalogued","The Preserved","The Flagged",
    "The Unremarkable","The Ordinary","The Daily","The Chronic","The Systemic",
    "The Repeated","The Predictable","The Expected","The Scheduled","The Routine",
    "The Measured","The Indexed","The Filed","The Logged","The Entered",
    "The Visible","The Legible","The Quantified","The Stamped","The Dated",
    "The Known","The Confirmed","The Verified","The Identified","The Classified",
    "The Acute","The Prolonged","The Extended","The Cumulative","The Progressive",
    "The Compounding","The Escalating","The Accelerating","The Deepening",
    "The Widening","The Spreading","The Encroaching","The Advancing","The Settling",
    "The Absolute","The Total","The Complete","The Thorough","The Comprehensive",
    "The Partial","The Fractured","The Broken","The Collapsed","The Fallen",
    "The Last","The First","The Only","The Single","The Solitary","The Lone",
    "The Heavy","The Dense","The Thick","The Dark","The Cold","The Empty",
    "The Hollow","The Blank","The Still","The Flat","The Gray","The Distant",
]

ARTIFACT_NOUNS = {
    "anger": [
        "Fury","Rupture","Flashpoint","Surge","Outburst","Spike","Burst","Flare","Break","Reaction",
        "Ignition","Detonation","Explosion","Eruption","Blowout","Discharge","Release","Fracture",
        "Collision","Impact","Strike","Blow","Crack","Split","Shatter","Tear","Rip","Snap",
        "Rebellion","Revolt","Refusal","Rejection","Defiance","Resistance","Confrontation","Challenge",
        "Boiling Point","Threshold","Limit","Edge","Boundary","Line","Wall","Ceiling","Floor","End",
        "Wave","Storm","Tempest","Torrent","Flood","Current","Tide","Force","Pressure","Charge",
    ],
    "tired": [
        "Collapse","Exhaustion","Decline","Drain","Depletion","Fade","Drop","Shutdown","Slowdown","Dimming",
        "Descent","Erosion","Degradation","Deterioration","Dissolution","Dissipation","Attrition","Wearing",
        "Flicker","Dimmer","Outage","Blackout","Failure","Halt","Stop","End","Cessation",
        "Quiet","Stillness","Silence","Pause","Rest","Stasis","Suspension","Dormancy","Hibernation",
        "Weight","Heaviness","Gravity","Burden","Load","Mass","Density","Thickness","Saturation",
        "Fog","Haze","Blur","Drift","Float","Limbo","Nowhere","Absence","Void",
    ],
    "sad": [
        "Lament","Grief","Weight","Absence","Loss","Echo","Hollow","Drift","Fade","Descent",
        "Mourning","Elegy","Requiem","Dirge","Farewell","Goodbye","Ending","Closing","Departure","Exit",
        "Silence","Void","Emptiness","Nothing","Gap","Space","Distance","Separation","Division","Break",
        "Ache","Wound","Scar","Mark","Trace","Remnant","Relic","Fragment","Shard","Piece",
        "Memory","Ghost","Shadow","Reflection","Echo","Impression","Imprint","Residue","Remainder","Afterimage",
        "Rain","Fog","Dark","Gray","Cold","Still","Heavy","Slow","Low","Down",
    ],

"frustrated": [
        "Impasse","Friction","Gridlock","Snag","Block","Jam","Loop","Clog","Barrier","Deadlock",
        "Wall","Ceiling","Floor","Limit","Boundary","Edge","Border","Line","Threshold","Cap",
        "Stall","Halt","Stop","Freeze","Lock","Bind","Trap","Cage","Cell","Enclosure",
        "Cycle","Circle","Spin","Repeat","Recurrence","Pattern","Routine","Rut","Groove",
        "Failure","Error","Mistake","Fault","Flaw","Bug","Glitch","Break","Crack","Gap",
        "Void","Absence","Hole","Disconnect","Mismatch","Conflict","Contradiction","Paradox",
    ],
    "anxious": [
        "Spiral","Dread","Tension","Pressure","Strain","Edge","Pulse","Tremor","Surge","Unease",
        "Current","Wave","Vibration","Frequency","Signal","Static","Noise","Interference","Distortion","Feedback",
        "Loop","Cycle","Spin","Vortex","Whirlpool","Undertow","Pull","Draw","Force",
        "Shadow","Silhouette","Shape","Form","Outline","Figure","Presence","Weight","Mass","Density",
        "Storm","Cloud","Front","System","Pressure","Low","Drop","Shift","Change","Event",
        "Clock","Count","Tick","Second","Moment","Instant","Brink","Verge","Threshold",
    ],
}

SUBTITLES = [
    "Recovered","Unknown Origin","Weekday Artifact","No Resolution","No Context",
    "Stable Condition","Catalogued","Preserved","Fragment","Unverified",
    "Condition Unknown","No Author","Partial Entry","Filed In Error","No Department",
    "Source Unclear","Duplicate","Archived","Shelved","Processed",
    "Date Inconsistent","Timestamp Missing","Entry Incomplete","Pages Absent","Cover Missing",
    "Recovered From Discard","Found At Workstation","Left Behind","Submitted Anonymously","No Signature",
    "Cross-Referenced: Nothing","No Matching Record","No Case Number","No Incident Report","No Escalation",
    "Reviewed Once","Noted And Closed","Flagged, No Action","Acknowledged, Shelved","Observed, Ignored",
    "Origin: Unknown","Classification: Pending","Status: Open","Outcome: Absent","Intervention: None",
    "No Follow-Up","No Referral","No Support","No Closure","No End",
    "Last In Series","Nothing Follows","End Of Record","Final Entry","Sequence Terminated",
    "Ongoing","Repeating","Chronic","Systemic","Cumulative",
    "High Load","Critical Condition","Below Threshold","Past Limit","At Capacity",
    "Weight: Unrecorded","Emotion: Flagged","Cause: Multiple","Impact: Undocumented","Recovery: Unknown",
]

ANOMALY_TYPES = ["GLITCH","REDACTED","ECHO","CORRUPTED","UNSTABLE","FRAGMENTED"]